// AUTO-GENERATED from schema-d1.json
export type Row = Record<string, any>;
export interface D1Model {
  findMany(args?: any): Promise<Row[]>;
  findFirst(args?: any): Promise<Row | null>;
  findUnique(args?: any): Promise<Row | null>;
  findFirstOrThrow(args?: any): Promise<Row>;
  create(args?: any): Promise<Row>;
  update(args?: any): Promise<Row>;
  updateMany(args?: any): Promise<{ count: number }>;
  upsert(args?: any): Promise<Row>;
  delete(args?: any): Promise<Row | null>;
  deleteMany(args?: any): Promise<{ count: number }>;
  createMany(args?: any): Promise<{ count: number }>;
  count(args?: any): Promise<number>;
  aggregate(args?: any): Promise<any>;
  groupBy(args?: any): Promise<Row[]>;
}
export interface PrismaLike {
  $transaction: any;
  user: D1Model;
  passwordResetToken: D1Model;
  category: D1Model;
  brand: D1Model;
  coupon: D1Model;
  couponUsage: D1Model;
  course: D1Model;
  lesson: D1Model;
  lessonProgress: D1Model;
  quiz: D1Model;
  question: D1Model;
  quizAttempt: D1Model;
  certificateTemplate: D1Model;
  certificate: D1Model;
  courseQuestion: D1Model;
  courseAnswer: D1Model;
  product: D1Model;
  productVariant: D1Model;
  enrollment: D1Model;
  review: D1Model;
  wishlist: D1Model;
  setting: D1Model;
  cart: D1Model;
  cartItem: D1Model;
  order: D1Model;
  orderItem: D1Model;
  paymentTransaction: D1Model;
  affiliate: D1Model;
  commission: D1Model;
  payout: D1Model;
  blogCategory: D1Model;
  blogPost: D1Model;
  blogComment: D1Model;
  forumCategory: D1Model;
  forumThread: D1Model;
  forumReply: D1Model;
  customerNote: D1Model;
  notification: D1Model;
  adminActivity: D1Model;
  instructorProfile: D1Model;
  instructorApplication: D1Model;
  courseWishlist: D1Model;
  tag: D1Model;
  courseTag: D1Model;
  productTag: D1Model;
  blogPostTag: D1Model;
  userAddress: D1Model;
  fAQ: D1Model;
}
